In [1]:
# https://www.tutorialspoint.com/numpy/index.htm

In [2]:
#Numpy -> Numerical Python'
# pip install numpy 

In [4]:
import numpy
import numpy as np

In [5]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# 2 D
a = np.array(
    [
        [1,2],
        [3,4]
    ]
)
a

array([[1, 2],
       [3, 4]])

In [9]:
a = np.array([1,2,3,4,5], ndmin=1)
a = np.array([1,2,3,4,5], ndmin=2)

a

array([[1, 2, 3, 4, 5]])

In [10]:
a =np.array([1,2,3], dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
# Array Atributes 
a = np.array([
    [1,2,3],
    [4,5,6]
])
a.shape

(2, 3)